# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceId',
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='key',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.AppUser', unique=True),
        ),
    ]
