# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20181203_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretkey',
            name='user',
        ),
        migrations.AddField(
            model_name='appuser',
            name='key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='SecretKey',
        ),
    ]
