# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20181205_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
