# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20181206_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='key',
            field=models.CharField(default='', max_length=32),
        ),
    ]
